Results:
  save_results: True
  save_dir: "results"
  save_trj: True
  save_trj_kf_intv: 10
  use_gui: False
  eval_rendering: True
  use_wandb: False
  color_refinement: True
  global_BA: False

Dataset:
  type: 'tum'
  sensor_type: 'monocular'
  depth_loss: True
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01

Training:
  init_itr_num: 1050
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  tracking_itr_num: 100
  mapping_itr_num: 150
  global_BA_itr_num: 500
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 1.0
  gaussian_reset: 2001
  size_threshold: 20
  kf_interval: 5
  window_size: 8
  pose_window: 3
  edge_threshold: 1.1
  rgb_boundary_threshold: 0.01
  alpha: 0.98
  kf_translation: 0.08
  kf_min_translation: 0.05
  kf_overlap: 0.90
  kf_cutoff: 0.3
  prune_mode: 'slam'
  prune_num: 1
  single_thread: False
  spherical_harmonics: False

  mapping_itr_nosingle: 10
  a_invalid: 0.5
  a_valid: 0.2

  lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001

opt_params:
  iterations: 30000
  position_lr_init: 0.0016
  position_lr_final: 0.00016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  # hsieh: added for deformable gs
  deformation_lr_init : 0.00016
  deformation_lr_final : 0.000016
  deformation_lr_delay_mult : 0.01
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002
  init_lr: 6

depth:
  patch_size: 10
  mean_threshold: 0.3
  std_threshold: 0.3
  error_threshold: 0.1
  final_error_threshold: 0.15
  min_accurate_pixels_ratio: 0.01

model_params:
  sh_degree: 0
  source_path: ""
  model_path: ""
  resolution: -1
  white_background: False
  data_device: "cuda"

pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False

# config for deformable gaussian splatting
deform_gs:
  # default:
  # ModelParams:
  extra_mark: "endonerf"
  camera_extent: 10

  # OptimizationParams:
  coarse_iterations: 0
  deformation_lr_init: 0.00016
  deformation_lr_final: 0.0000016
  deformation_lr_delay_mult: 0.01
  iterations: 3000
  percent_dense: 0.01
  opacity_reset_interval: 3000
  position_lr_max_steps: 4000
  prune_interval: 3000

  # ModelHiddenParams:
  curve_num: 17
  ch_num: 10
  init_param: 0.01


  # OptimizationParams
  dataloader: False
  iterations : 30000
  position_lr_init : 0.00016
  position_lr_final : 0.0000016
  position_lr_delay_mult : 0.01
  position_lr_max_steps : 20000
  deformation_lr_init : 0.00016
  deformation_lr_final : 0.000016
  deformation_lr_delay_mult : 0.01
  # grid_lr_init : 0.0016
  # grid_lr_final : 0.00016

  feature_lr : 0.0025
  opacity_lr : 0.05
  scaling_lr : 0.005
  rotation_lr : 0.001
  percent_dense : 0.01
  weight_constraint_init: 1
  weight_constraint_after : 0.2
  weight_decay_iteration : 5000
  opacity_reset_interval : 3000
  densification_interval : 100
  densify_from_iter : 500
  densify_until_iter : 15000
  densify_grad_threshold_coarse : 0.0002
  densify_grad_threshold_fine_init : 0.0002
  densify_grad_threshold_after : 0.0002
  pruning_from_iter : 500
  pruning_interval : 100
  opacity_threshold_coarse : 0.005
  opacity_threshold_fine_init : 0.005
  opacity_threshold_fine_after : 0.005